### ISSUE TITLE
Missing Py2k/Windows build b/c of snakebite[kerberos]

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/girder-feedstock#1]
We've skipped the build of girder for windows and `py2k` because of a dependency on [`snakebite`](https://pypi.python.org/pypi/snakebite/) in `py2k` builds. There's no conda-forge build of the library yet, and the default from anaconda doesn't support windows.

Per general conda-forge thinking, we'd want to build `snakebite` to support all extensions - that is `snakebite[kerberos]` as well as standard `snakebite`. Doing so would require a build of [`python-krbV`](https://pypi.python.org/pypi/python-krbV/1.0.90), which has given some trouble.

One fix for this would be to build `snakebite` and temporarily dodge on supporting `snakebite[kerberos]`. Something to think about.

**Comment by jan-janssen** [comment]
I guess this issue is fixed now with the noarch package.
